### PR TITLE
Confirm exit screen

### PR DESCRIPTION
**Pull request by toughmuffin12**
Adds a confirm exit screen when exiting the from the pause menu

### CODE REVIEW

**Comment by Quillo123** [comment]
I cannot exit from the tutorial scene. The pause menu seems to break when clicking exit.

**Review by Quillo123 — CHANGES_REQUESTED** [review]
Fix tutorial pause menu

**Comment by toughmuffin12** [comment]
Tutorial Pause Menu should be fixed but idk if it will update the pull request. Should I reopen it?

**Review by Quillo123 — APPROVED** [review]
It works now. Approved

**Pull request merged**
